### ISSUE TITLE
Want to Add Images to Website 

### ISSUE THREAD

**Issue by Adidem23** [sanjeevpurigoswami/RedStore#2]
I want to add Images which are missing in website And  Can we Write React or ViteJs for making Frontend and for Ui . Because Adding all Fucntionalities will not be done with Only HTML and CSS . For Enabling the Add to Cart Also We Will requiring Redux toolkit so , Can We ??

**Comment by Sanjeev-Puri** [comment]
@Adidem23 

I have uploaded images which i have used in this project , you can use that and if you thik that your idea will work please go ahead. All the best

**Comment by Adidem23** [comment]
I will Try to Add Vite js code Which will More beneficial for more Advanced Features Thank You !!
