### ISSUE TITLE
Convert The whole website Code In ReactJs

### ISSUE THREAD

**Issue by Adidem23** [sanjeevpurigoswami/RedStore#7]
I want to use ReactJS for the Implementation of the our REDSTORE Because Adding oto CART and Adding Cart According to user will be Very Complex in Html , Css so I want to do it in react or viteJs

**Comment by Sanjeev-Puri** [comment]
@Adidem23 
Go ahead i have assigned this to you make cart section working
All the best

**Comment by Adidem23** [comment]
I have not completed sorry brother

**Comment by Sanjeev-Puri** [comment]
> I have not completed sorry brother 

It's ok bro take your time and go ahead with slower speed no problem at all
